FROM python:3.13.6-slim-bookworm

# Variables
ARG username=dev
ARG path=/development

LABEL org.opencontainers.image.source="https://github.com/solairen/helm-chart-updater"
LABEL org.opencontainers.image.description="Update Chart.yaml file"
LABEL org.opencontainers.image.authors="Michał Oleszek michal@michaloleszek.com"
LABEL org.opencontainers.image.licenses=MIT
LABEL release=development

# Environment
ENV USER=${username}
ENV USERNAME=${username}

# Use user root
USER root

# Create folders
RUN mkdir ${path} \
  # Install packages
  && apt update && apt upgrade -y && apt install curl=7.88.1-10+deb12u12 git=1:2.39.5-0+deb12u2 openssh-server=1:9.2p1-2+deb12u6 gpg=2.2.40-1.1 locales=2.36-9+deb12u10 -y && apt clean \
  # Install upgrade pip
  && pip install --upgrade pip \
  && pip install pygithub==2.6.1 pyyaml==6.0.2 pre-commit==4.2.0 \
  # Install hadolint
  && curl -L https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 -o /usr/local/bin/hadolint \
  && chmod +x /usr/local/bin/hadolint \
  # Configure locales
  && echo "LC_ALL=en_US.UTF-8" >> /etc/environment \
  && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
  && echo "LANG=en_US.UTF-8" > /etc/locale.conf \
  && locale-gen en_US.UTF-8 \
  # Add user dev
  && useradd -ms /bin/bash ${username} \
  && chown -R ${username}:${username} ${path} \
  # Install starship
  && curl -fsSL https://starship.rs/install.sh -o /tmp/install.sh \
  && sh /tmp/install.sh -y \
  && mkdir /home/${username}/.config \
  && starship preset no-empty-icons -o /home/${username}/.config/starship.toml \
  && echo '[terraform]' >> /home/${username}/.config/starship.toml \
  && echo "format = '([(\$version | workspace: \$workspace)](\$style))'" >> /home/${username}/.config/starship.toml \
  && echo 'eval "$(starship init bash)"' >> /home/${username}/.bashrc

COPY . ${path}

RUN chown -R ${username}:${username} ${path}

# Use user dev
USER dev

# Workdir
WORKDIR ${path}

# Entrypoint
ENTRYPOINT [ "bash" ]
