FROM python:3.12-slim

# Variables
ARG username=dev
ARG path=/development

LABEL org.opencontainers.image.source="https://github.com/solairen/helm-chart-updater"
LABEL org.opencontainers.image.description="Update Chart.yaml file"
LABEL org.opencontainers.image.authors="Michał Oleszek michal@michaloleszek.com"
LABEL org.opencontainers.image.licenses=MIT
LABEL release=development

# Environment
ENV USER=${username}
ENV USERNAME=${username}

# Use user root
USER root

# Create folders
RUN mkdir ${path} \
  # Install packages
  && apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y --no-install-recommends curl git openssh-server gpg locales libatomic1 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  # Install upgrade pip
  && pip install --no-cache-dir --upgrade pip==24.0 \
  && pip install --no-cache-dir pygithub==2.6.1 pyyaml==6.0.2 pre-commit==4.2.0 \
  # Install hadolint
  && ARCH=$(dpkg --print-architecture) \
  && if [ "$ARCH" = "amd64" ]; then HADOLINT_ARCH="x86_64"; else HADOLINT_ARCH="arm64"; fi \
  && curl -L https://github.com/hadolint/hadolint/releases/download/v2.14.0/hadolint-Linux-${HADOLINT_ARCH} -o /usr/local/bin/hadolint \
  && chmod +x /usr/local/bin/hadolint \
  # Configure locales
  && echo "LC_ALL=en_US.UTF-8" >> /etc/environment \
  && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
  && echo "LANG=en_US.UTF-8" > /etc/locale.conf \
  && locale-gen en_US.UTF-8 \
  # Add user dev
  && useradd -ms /bin/bash ${username} \
  && chown -R ${username}:${username} ${path} \
  # Install starship
  && curl -fsSL https://starship.rs/install.sh -o /tmp/install.sh \
  && sh /tmp/install.sh -y \
  && mkdir /home/${username}/.config \
  && starship preset no-empty-icons -o /home/${username}/.config/starship.toml \
  && echo "[terraform]" >> /home/${username}/.config/starship.toml \
  && echo "format = '([(\$version | workspace: \$workspace)](\$style))'" >> /home/${username}/.config/starship.toml \
  && echo 'eval "$(starship init bash)"' >> /home/${username}/.bashrc

COPY . ${path}

RUN chown -R ${username}:${username} ${path}

# Use user dev
USER dev

# Workdir
WORKDIR ${path}

# Entrypoint
ENTRYPOINT [ "bash" ]
